/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author garym
 */
public class jfRecursos extends javax.swing.JFrame {

    /**
     * Creates new form jfRecursos
     */
    public jfRecursos() {
        initComponents();
        preencherTabela("src/main/data/recursos/recursos.txt");
    }
    
    private void preencherTabela(String src){
        DefaultTableModel dtmRecursos = (DefaultTableModel)jTRecursos.getModel();
        try{
            BufferedReader buff = new BufferedReader(new FileReader(src));
            String[] dados = new String[3];
            
            while(buff.ready()){
                String linha= buff.readLine();
                dados = linha.split(",");
                dtmRecursos.addRow(dados);
            }
            buff.close();
        }catch(IOException ioe){
            ioe.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTRecursos = new javax.swing.JTable();
        botaoNovoRecurso = new javax.swing.JButton();
        campoTextoNomeRecurso = new javax.swing.JTextField();
        campoTextoTipoRecurso = new javax.swing.JTextField();
        campoTextoCategoriaRecurso = new javax.swing.JTextField();
        labelRecurso = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        botaoExcluirRecurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(450, 250));

        jTRecursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recurso", "Tipo", "Descrição"
            }
        ));
        jTRecursos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTRecursos);

        botaoNovoRecurso.setText("Cadastrar Recurso");

        campoTextoNomeRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNomeRecursoActionPerformed(evt);
            }
        });

        campoTextoCategoriaRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoCategoriaRecursoActionPerformed(evt);
            }
        });

        labelRecurso.setText("Recurso");

        labelTipo.setText("Tipo");

        labelDescricao.setText("Descrição");

        botaoExcluirRecurso.setText("Excluir Recurso");
        botaoExcluirRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirRecursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTextoNomeRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRecurso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTextoTipoRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDescricao)
                            .addComponent(campoTextoCategoriaRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoNovoRecurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoExcluirRecurso, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRecurso)
                    .addComponent(labelTipo)
                    .addComponent(labelDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoNomeRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoTipoRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTextoCategoriaRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoNovoRecurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluirRecurso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoCategoriaRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoCategoriaRecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoCategoriaRecursoActionPerformed

    private void campoTextoNomeRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNomeRecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNomeRecursoActionPerformed

    private void botaoExcluirRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirRecursoActionPerformed
        int selecionado = jTRecursos.getSelectedRow();
        System.out.println(selecionado);
        DefaultTableModel dtmRecursos = (DefaultTableModel)jTRecursos.getModel();
        try{
            BufferedReader buff = new BufferedReader(new FileReader("src/main/data/recursos/recursos.txt"));
            String[] dados = new String[3];
            
            while(buff.ready()){
                String linha= buff.readLine();
                dados = linha.split(",");
                dtmRecursos.addRow(dados);
            }
            buff.close();
        }catch(IOException ioe){
            ioe.printStackTrace();
        }
        dtmRecursos.removeRow(selecionado); 
    }//GEN-LAST:event_botaoExcluirRecursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfRecursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluirRecurso;
    private javax.swing.JButton botaoNovoRecurso;
    private javax.swing.JTextField campoTextoCategoriaRecurso;
    private javax.swing.JTextField campoTextoNomeRecurso;
    private javax.swing.JTextField campoTextoTipoRecurso;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTRecursos;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelRecurso;
    private javax.swing.JLabel labelTipo;
    // End of variables declaration//GEN-END:variables
}
